src/Domain/Article/Entity/ArticleInterface.php
<?php

namespace App\Domain\Article\Entity;

use App\Domain\Security\Entity\UserEntityInterface;

interface ArticleInterface
{
    public function getId(): ?int;

    public function setId(?int $id): ArticleInterface;

    public function getSlug(): ?string;

    public function setSlug(?string $slug): ArticleInterface;

    public function getTitle(): ?string;

    public function setTitle(?string $title): ArticleInterface;

    public function getDescription(): ?string;

    public function setDescription(?string $description): ArticleInterface;

    public function getContent(): ?string;

    public function setContent(?string $content): ArticleInterface;

    public function getCategory(): ?TaxonomyInterface;

    public function setCategory(?TaxonomyInterface $category): static;

    /**
     * @return TaxonomyInterface[]
     */
    public function getTags(): mixed;

    /**
     * @param TaxonomyInterface[] $tags
     */
    public function addTags(array $tags): ArticleInterface;

    public function getOwner(): ?UserEntityInterface;

    public function setOwner(?UserEntityInterface $user): static;
}

templates/front/macros/content/article-large-block.html.twig
{% macro renderLarge(article) %}

    {% import 'front/macros/links/taxonomy-link-list.html.twig' as taxonomyLinks %}

    <article id="article-{{ article.id }}" class="row mb-5">
        <div class="col-12">
            <div class="post-slider">
                <img loading="lazy" src="https://picsum.photos/1200/600" class="img-fluid" alt="post-thumb">
            </div>
        </div>
        <div class="col-12 mx-auto">
            <h3><a class="post-title" href="{{ path('article_show', {id: article.id}) }}">{{ article.title }}</a></h3>
            <ul class="list-inline post-meta mb-4">
                <li class="list-inline-item"><i class="ti-user mr-2"></i>
                    <a href="#">{{ article.owner.firstname }} {{ article.owner.lastname }}</a>
                </li>
                <li class="list-inline-item">Date : {{ article.createdAt|date("F d, Y") }}</li>
                {% if article.category %}
                    <li class="list-inline-item">Category : <a href="{{ path('category_show', {slug: article.category.slug}) }}" class="ml-1">{{ article.category.title }} </a></li>
                {% endif %}
                {% if article.tags|length > 0 %}
                    <li class="list-inline-item">Tags : {{ taxonomyLinks.generate(article.tags, 'tag_show') }}</li>
                {% endif %}
            </ul>
            <p>{{ article.description|u.truncate(500, '...') }}</p>
            <a href="{{ path('article_show', {id: article.id}) }}" class="btn btn-outline-primary">Continue Reading</a>
        </div>
    </article>
{% endmacro %}

templates/front/macros/content/article-medium-block.html.twig
{% macro renderMedium(article) %}

    {% import 'front/macros/links/taxonomy-link-list.html.twig' as taxonomyLinks %}

    <article id="article-{{ article.id }}" class="row mb-5">
        <div class="col-md-4 mb-4 mb-md-0">
            <div class="post-slider slider-sm">
                <img loading="lazy" src="https://picsum.photos/230/230" class="img-fluid" alt="post-thumb" style="height:230px; object-fit: cover;">
            </div>
        </div>
        <div class="col-md-8">
            <h3 class="h5"><a class="post-title" href="{{ path('article_show', {id: article.id}) }}">{{ article.title }}</a></h3>
            <ul class="list-inline post-meta mb-2">
                <li class="list-inline-item"><i class="ti-user mr-2"></i>
                    <a href="#">{{ article.owner.firstname }} {{ article.owner.lastname }}</a>
                </li>
                <li class="list-inline-item">Date : {{ article.createdAt|date("F d, Y") }}</li>
                {% if article.category %}
                    <li class="list-inline-item">Categories : <a href="{{ path('category_show', {slug: article.category.slug}) }}" class="ml-1">{{ article.category.title }} </a></li>
                {% endif %}
                {% if article.tags|length > 0 %}
                    <li class="list-inline-item">Tags :{{ taxonomyLinks.generate(article.tags, 'tag_show') }}</li>
                {% endif %}
            </ul>
            <p>{{ article.description|u.truncate(250, '...') }}</p>
            <a href="{{ path('article_show', {id: article.id}) }}" class="btn btn-outline-primary">Continue Reading</a>
        </div>
    </article>
{% endmacro %}